In [1]:
import numpy as np

In [2]:
# Problem 4.1 - Array Creation solutions

# 1. Initialize an empty array with size 2x2
empty_2x2 = np.empty((2,2))
empty_2x2

array([[2.88430792e-315, 0.00000000e+000],
       [2.12199579e-314, 5.30886346e+180]])

In [3]:
# 2. Initialize an all one array with size 4x2
ones_4x2 = np.ones((4,2))
ones_4x2


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
# 3. Return a new array of given shape and type, filled with fill value (np.full)
filled_3x3 = np.full((3,3), 7)
filled_3x3

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [5]:
# 4. Return a new array of zeros with same shape and type as a given array (np.zeros_like)
arr_example = np.array([[1,2,3],[4,5,6]])
zeros_like_example = np.zeros_like(arr_example)
zeros_like_example

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:

# 5. Return a new array of ones with same shape and type as a given array (np.ones_like)
ones_like_example = np.ones_like(arr_example)
ones_like_example


array([[1, 1, 1],
       [1, 1, 1]])

In [7]:
# 6. For an existing list new_list = [1,2,3,4] convert to a numpy array
new_list = [1,2,3,4]
arr_from_list = np.array(new_list)
arr_from_list, arr_from_list.dtype

(array([1, 2, 3, 4]), dtype('int64'))

In [8]:
# 1. Create an array with values ranging from 10 to 49
arr_10_49 = np.arange(10,50)
arr_10_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
# 2. Create a 3x3 matrix with values ranging from 0 to 8
mat_3x3_0_8 = np.arange(9).reshape(3,3)
mat_3x3_0_8


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 3. Create a 3x3 identity matrix
eye_3 = np.eye(3)
eye_3


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# 4. Create a random array of size 30 and find the mean
rand30 = np.random.random(30)
mean_rand30 = rand30.mean()
mean_rand30


np.float64(0.5866486340421526)

In [14]:
# 5. Create a 10x10 array with random values and find min and max
rand_10x10 = np.random.random((10,10))
rand_min = rand_10x10.min()
rand_max = rand_10x10.max()
rand_min, rand_max

(np.float64(0.002360883961073368), np.float64(0.9910862677662073))

In [13]:
# 6. Create a zero array of size 10 and replace 5th element with 1
zeros_10 = np.zeros(10)
zeros_10[4] = 1
zeros_10


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
reversed_arr


array([0, 4, 0, 0, 2, 1])

In [16]:
# 8. Create a 2d array with 1 on border and 0 inside
def bordered(n, m):
    A = np.ones((n,m), dtype=int)
    if n>2 and m>2:
        A[1:-1,1:-1] = 0
    elif n>2 and m<=2:
        A[1:-1,:] = 0
    elif m>2 and n<=2:
        A[:,1:-1] = 0
    return A

bordered_6x6 = bordered(6,6)
bordered_6x6


array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

In [17]:
# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [18]:
# Given arrays:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

x, y, v, w

(array([[1, 2],
        [3, 5]]),
 array([[5, 6],
        [7, 8]]),
 array([ 9, 10]),
 array([11, 12]))

In [19]:
# 1. Add the two arrays x + y
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
add_xy = x + y
add_xy

array([[ 6,  8],
       [10, 13]])

In [20]:
# 2. Subtract the two arrays x - y
sub_xy = x - y
sub_xy


array([[-4, -4],
       [-4, -3]])

In [21]:
# 3. Multiply the array with any integer (elementwise), choose 3
mul_x = x * 3
mul_x


array([[ 3,  6],
       [ 9, 15]])

In [22]:
# 4. Find the square of each element of the array (elementwise)
square_x = x**2
square_x

array([[ 1,  4],
       [ 9, 25]])

In [24]:
# 5. Dot products: v·w, x·v (error expected), x·y (matrix multiplication)
v = np.array([9,10])
w = np.array([11,12])

dot_vw = np.dot(v, w)

x = np.array([[1,2],[3,5]])
x_dot_v = x.dot(v)
x_dot_y = x.dot(y)
dot_vw, x_dot_v, x_dot_y

(np.int64(219),
 array([29, 77]),
 array([[19, 22],
        [50, 58]]))

In [25]:
# 6. Concatenate x and y along row (axis=0) and v and w along column (turn vectors to column first)
concat_xy_axis0 = np.concatenate((x, y), axis=0)
concat_vw_col = np.column_stack((v, w))
concat_xy_axis0, concat_vw_col

(array([[1, 2],
        [3, 5],
        [5, 6],
        [7, 8]]),
 array([[ 9, 11],
        [10, 12]]))

In [26]:
# 7. Concatenate x and v; observe and explain

try:
    np.concatenate((x, v), axis=1)
except Exception as e:
    explanation = str(e)

v_col = v.reshape((2,1))
concatenated_ok = np.concatenate((x, v_col), axis=1)
explanation, concatenated_ok

('all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)',
 array([[ 1,  2,  9],
        [ 3,  5, 10]]))

In [27]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A, B

(array([[3, 4],
        [7, 8]]),
 array([[5, 3],
        [2, 1]]))

In [28]:
# 1. Prove A * A^{-1} = I (matrix inverse)
A = np.array([[3,4],[7,8]], dtype=float)
A_inv = np.linalg.inv(A)
I_calc = A.dot(A_inv)
I_calc_rounded = np.round(I_calc, decimals=10)
A_inv, I_calc_rounded

(array([[-2.  ,  1.  ],
        [ 1.75, -0.75]]),
 array([[1., 0.],
        [0., 1.]]))

In [29]:
# 2. Show AB != BA (matrix multiplication is not generally commutative)
AB = A.dot(B)
BA = B.dot(A)
AB, BA, np.array_equal(AB, BA)

(array([[23., 13.],
        [51., 29.]]),
 array([[36., 44.],
        [13., 16.]]),
 False)

In [30]:
# 3. Prove (AB).T = B.T @ A.T
lhs = (A.dot(B)).T
rhs = B.T.dot(A.T)
lhs, rhs, np.array_equal(lhs, rhs)


(array([[23., 51.],
        [13., 29.]]),
 array([[23., 51.],
        [13., 29.]]),
 True)

In [31]:
# Solve system of linear equations using matrix form (AX = B)
# Equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9
A_mat = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]], dtype=float)
B_vec = np.array([-1, -3, 9], dtype=float)
solution = np.linalg.solve(A_mat, B_vec)
solution


array([ 2.,  1., -2.])

In [32]:
# Solve same system using inverse (np.linalg.inv) to demonstrate
A_inv = np.linalg.inv(A_mat)
solution_using_inv = A_inv.dot(B_vec)
solution_using_inv

array([ 2.,  1., -2.])

In [33]:
import time
import random

N = 1_000_000

# Prepare data
list_a = [random.random() for _ in range(N)]
list_b = [random.random() for _ in range(N)]

# 1. Element-wise addition - lists
t0 = time.time()
list_add = [a + b for a, b in zip(list_a, list_b)]
t1 = time.time()
time_list_add = t1 - t0

# 1. Element-wise addition - numpy
arr_a = np.array(list_a)
arr_b = np.array(list_b)
t0 = time.time()
np_add = arr_a + arr_b
t1 = time.time()
time_np_add = t1 - t0

# 2. Element-wise multiplication - lists
t0 = time.time()
list_mul = [a * b for a, b in zip(list_a, list_b)]
t1 = time.time()
time_list_mul = t1 - t0

# 2. Element-wise multiplication - numpy
t0 = time.time()
np_mul = arr_a * arr_b
t1 = time.time()
time_np_mul = t1 - t0

# 3. Dot product - lists
t0 = time.time()
dot_list = sum(a*b for a,b in zip(list_a, list_b))
t1 = time.time()
time_list_dot = t1 - t0

# 3. Dot product - numpy (using np.dot)
t0 = time.time()
dot_np = arr_a.dot(arr_b)
t1 = time.time()
time_np_dot = t1 - t0

# 4. Matrix multiplication: pure-python smaller size, numpy 1000x1000
size_small = 200  # smaller size for pure Python to keep runtime reasonable here
# pure-Python matrix multiplication (size_small x size_small)
A_list = [[random.random() for _ in range(size_small)] for _ in range(size_small)]
B_list = [[random.random() for _ in range(size_small)] for _ in range(size_small)]

def matmul_list(A, B):
    n = len(A)
    m = len(B[0])
    p = len(B)
    C = [[0.0]*m for _ in range(n)]
    for i in range(n):
        Ai = A[i]
        for k in range(p):
            Bk = B[k]
            aik = Ai[k]
            rowC = C[i]
            for j in range(m):
                rowC[j] += aik * Bk[j]
    return C

t0 = time.time()
C_list = matmul_list(A_list, B_list)
t1 = time.time()
time_list_matmul = t1 - t0

# numpy matrix multiplication 1000x1000
size_big = 1000
A_np_big = np.random.random((size_big, size_big))
B_np_big = np.random.random((size_big, size_big))
t0 = time.time()
C_np_big = A_np_big.dot(B_np_big)
t1 = time.time()
time_np_matmul = t1 - t0

# Summarize times (seconds)
times = {
    'list_add': time_list_add,
    'numpy_add': time_np_add,
    'list_mul': time_list_mul,
    'numpy_mul': time_np_mul,
    'list_dot': time_list_dot,
    'numpy_dot': time_np_dot,
    'list_matmul_{}x{}'.format(size_small, size_small): time_list_matmul,
    'numpy_matmul_{}x{}'.format(size_big, size_big): time_np_matmul
}
times


{'list_add': 0.11267614364624023,
 'numpy_add': 0.008235692977905273,
 'list_mul': 0.15949177742004395,
 'numpy_mul': 0.010491609573364258,
 'list_dot': 0.13457250595092773,
 'numpy_dot': 0.003271818161010742,
 'list_matmul_200x200': 0.7779743671417236,
 'numpy_matmul_1000x1000': 0.05829000473022461}